version: '3.6'

services:
  frontend: #name of the first service
    build: ./client # specify the directory of the Dockerfile
    ports:
      - '4200:4200'
      - '49153:49153'
    environment:
      - NODE_ENV=dev
    volumes:
      - "./client:/app/client"
    container_name: front-container
    restart: always
  backend: #name of the second service
    build: ./server # specify the directory of the Dockerfile
    ports:
      - "5000:5000" #specify ports forewarding
    container_name: back-container
    restart: always
    environment:
      - MONGO_URL=mongodb://api:docker1234@mongo
      - JWT=Dreamer06
      - PORT=5000
    links:
      - mongo
  mongo : 
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234