version: "3.6"

services:
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=dev
    volumes:
      - "./client:/app/client"
    container_name: front-container
    restart: always
  cors-proxy:
    image: redocly/cors-anywhere
    ports:
      - "8080:8080"
    container_name: cors-proxy
    restart: always
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - "./server:/app/server"
    container_name: back-container
    restart: always
    environment:
      - MONGO_URL=mongodb://api:docker1234@mongo
      - JWT=Dreamer06
      - PORT=5000
      - MAIL_LOG=7fcbbc720647509be50be2e73c4a3dde
      - MAIL_PASS=565163faf9fc084693530f6491185d53
      - MAIL_HOST=in-v3.mailjet.com
      - MAIL_HOST_URL=http://localhost
    links:
      - mongo
  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
