version: "3.6"

services:
  cors-proxy:
    image: redocly/cors-anywhere
    ports:
      - "8080:8080"
    container_name: cors-proxy
    restart: always
  backend:
    build: ./server
    ports:
      - "5000:5000"
    container_name: back-lollimemo-container
    restart: always
    environment:
      - MONGO_URL=mongodb://api:docker1234@mongo?directConnection=true
      - JWT=Dreamer06
      - PORT=5000
      - MAIL_LOG=7fcbbc720647509be50be2e73c4a3dde
      - MAIL_PASS=565163faf9fc084693530f6491185d53
      - MAIL_HOST=in-v3.mailjet.com
      - MAIL_HOST_URL=http://217.182.171.139
    links:
      - mongo
  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27018:27018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - "4001:4001"
    container_name: front-lollimemo-container
    restart: always
