version: '3.6'

services:
  backend: #name of the second service
    build: ./server # specify the directory of the Dockerfile
    ports:
      - "5000:5000" #specify ports forewarding
    container_name: back-container
    restart: always
    environment:
      - MONGO_URL=mongodb://api:docker1234@mongo?directConnection=true
      - JWT=Dreamer06
      - PORT=5000
      - MAIL_LOG=7fcbbc720647509be50be2e73c4a3dde
      - MAIL_PASS=565163faf9fc084693530f6491185d53
      - MAIL_HOST=in-v3.mailjet.com
      - MAIL_HOST_URL=http://217.182.171.139
    links:
      - mongo
  mongo : 
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
  frontend: #name of the first service
    build: 
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - '80:80'
    container_name: front-container
    restart: always